apiVersion: v1
kind: Service
metadata:
  name: nginx-svc
  labels:
    env: dev
spec:
  type: NodePort  # Changed from LoadBalancer to NodePort
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30008  # Specify a port in the range 30000-32767 or let Kubernetes assign one automatically
  selector:
    env: dev
